name: wp_player
description: "Wavepaths"
# Prevents app from being published to pub.dev by using `flutter pub publish`
publish_to: "none" # Don't remove this line

# Update both versionName (seen by user) and versionCode on new version
# version: major.minor.patch+yyyymmddaa - where aa is two numbered version on this date
version: 3.0.6+2026032402

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  ffi: ^2.1.4
  flutter_riverpod: ^3.0.0
  go_router: ^17.0.0
  path_provider: ^2.1.5
  synchronized: ^3.3.1
  logger: ^2.5.0
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  http: ^1.4.0
  uuid: ^4.5.1
  socket_io_client: ^1.0.0
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0+1
  mutex: ^3.1.0
  app_links: ^6.4.0
  hooks_riverpod: ^3.0.0
  mobile_scanner: ^7.0.1 # check for IOS https://pub.dev/packages/mobile_scanner
  loading_animation_widget: ^1.3.0
  path: ^1.9.1
  async: ^2.13.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2 # check for IOS https://pub.dev/packages/url_launcher
  device_info_plus: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "app_icon"
  image_path: "assets/icons/icon.png"
  # ios: true # Uncomment this line if you want to generate iOS icons
  windows:
    generate: false # another one is used
  macos:
    generate: true
    image_path: "assets/icons/icon_macos.png"


flutter:
  uses-material-design: true
  assets: # Not recursive - should include subfolders manually
    - assets/audio/
    - assets/images/
    - assets/images/noise/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont.ttf
          style: italic
