name: "Android build" # TODO: add and deploy (when and if applicable)
on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  build_sign_deploy:
    runs-on: ubuntu-latest
    steps:
      # ----------------------------------------------------
      # setup

      - uses: actions/checkout@v4

      - name: Add Java 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Add Dart (Flutter)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # ----------------------------------------------------
      # pre building and building

      - name: Decode and decrypt signing key
        env:
          KEY_ENCRYPTION_PASSWORD: ${{ secrets.KEY_ENCRYPTION_PASSWORD }}
          ENCRYPTED_KEY: ${{ secrets.ENCRYPTED_KEY }}
        run: |
          echo "::add-mask::$KEY_ENCRYPTION_PASSWORD"
          echo "::add-mask::$ENCRYPTED_KEY"
          printf '%s' "$ENCRYPTED_KEY" > wavepaths.keystore.jks.enc.b64
          base64 -d wavepaths.keystore.jks.enc.b64 > wavepaths.keystore.jks.enc
          openssl enc -d -camellia-256-cbc -pbkdf2 -in wavepaths.keystore.jks.enc -out wavepaths.keystore.jks -pass env:KEY_ENCRYPTION_PASSWORD
          rm -f wavepaths.keystore.jks.enc.b64
          rm -f wavepaths.keystore.jks.enc

      - name: Add key.properties file
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ vars.KEY_ALIAS }}
        run: |
          echo "::add-mask::$STORE_PASSWORD"
          echo "::add-mask::$KEY_PASSWORD"
          printf 'storePassword=%s\nkeyPassword=%s\nkeyAlias=%s\nstoreFile=../../wavepaths.keystore.jks\n' "$STORE_PASSWORD" "$KEY_PASSWORD" "$KEY_ALIAS" > android/key.properties

      - name: Flutter build
        run: flutter build appbundle --release

      - name: Cleanup sensitive files
        if: always()
        run: |
          rm -f wavepaths.keystore.jks
          rm -f android/key.properties

      # ----------------------------------------------------
      # publishing

      - name: Get release version
        id: version
        run: echo "version=$(grep -Po '^\s*version:\s*\K\S+' pubspec.yaml | sed 's/+/./g')" >> "$GITHUB_OUTPUT"

      # TODO: replace with Workload identity authentication https://github.com/r0adkll/upload-google-play
      - name: Publish to Play Console
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: "$SERVICE_ACCOUNT_JSON"
          packageName: "com.wavepaths.player"
          releaseFiles: "build/app/outputs/bundle/release/app-release.aab"
          track: "qa" # internal testing

      - name: Add git release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v.${{ steps.version.outputs.version }}"
          name: "v.${{ steps.version.outputs.version }}"
          files: "build/app/outputs/bundle/release/app-release.aab"
